// Forked from https://github.com/knowlesc/scattergories-generator/blob/master/src/data/CategoryList.ts
var categories = [
  '3-letter Words',
  '5-letter Words',
  'A bird',
  'A boy’s name',
  'A drink',
  'A fish',
  'A girl’s name',
  'A relative',
  'A river',
  'Abbreviations',
  'Acronyms',
  'Action Words',
  'Adjectives',
  'After School Activities',
  'An animal',
  'Animal noises',
  'Animals Found In Foreign Lands',
  'Animals From TV/Movies/Books',
  'Animals In Advertising',
  'Animals in books or movies',
  'Animals That Fly',
  'Animals That Swim',
  'Appetizers',
  'Appliances',
  'Artists',
  'Athletes In Commercials',
  'Authors',
  'Awards/ceremonies',
  'Baby foods',
  'Bad habits',
  'Baseball Player',
  'Beers',
  'Birds',
  'Board games',
  'Bodies of water',
  'Books / Movies About Sports',
  'Breakfast Cereals',
  'Breakfast foods',
  'Cancelled TV Shows',
  'Canned Foods',
  'Capitals',
  'Card games',
  'Carnival/Fair Foods',
  'Cars',
  'Cartoon characters',
  'Celebrities You\'d Like To Meet',
  'Celebrities',
  'Children’s books',
  'Children’s TV Shows',
  'Chinese Foods',
  'Christmas songs',
  'Cities',
  'Clothing',
  'Cocktails',
  'Cold Climates',
  'Colleges/Universities',
  'Colors',
  'Comedy Shows/Sitcoms',
  'Computer parts',
  'Computer programs',
  'Cooking utensils',
  'Cosmetics/Toiletries',
  'Countries',
  'Couples',
  'Crimes',
  'Dangerous Animals',
  'Dangerous Professions',
  'Daytime TV Shows',
  'Diet foods',
  'Diseases',
  'Disgusting Things To Eat',
  'Drugs that are abused',
  'Electronic gadgets',
  'Ethnic foods',
  'Excuses for being late',
  'Famous Children',
  'Famous duos and trios',
  'Fast Foods',
  'Fears',
  'Female Athletes',
  'Female TV Stars',
  'Fictional characters',
  'Fictitious Places',
  'Fish',
  'Flowers',
  'Food Found In A Deli',
  'Food/Drink that is green',
  'Foods Found In Casseroles',
  'Foods you eat raw',
  'Football Player',
  'Footware',
  'Foreign words used in English',
  'Foreign Words',
  'Foriegn cities',
  'Four-legged Animals',
  'Fried Foods',
  'Fruits',
  'Game terms',
  'Games',
  'Gifts For The Bride & Groom',
  'Gifts',
  'Green Foods & Drinks',
  'Halloween costumes',
  'Health Foods',
  'Heroes',
  'Historic events',
  'Historical Figures',
  'Hobbies',
  'Holiday Activities',
  'Holidays',
  'Honeymoon spots',
  'Household chores',
  'Ice cream flavors',
  'In the NWT (Northwest Territories, Canada)',
  'Insects',
  'Internet lingo',
  'Islands',
  'Italian Foods',
  'Items in a catalog',
  'Items in a kitchen',
  'Items in a suitcase',
  'Items in a vending machine',
  'Items in this room',
  'Items you save up to buy',
  'Items you take on a road trip',
  'Kinds of candy',
  'Kinds of soup',
  'Last Names',
  'Leisure activities',
  'Long Running TV Shows',
  'Low Calorie Foods',
  'Magazines',
  'Mall TV Stars',
  'Mascots',
  'Math terms',
  'Menu items',
  'Mexican Foods',
  'Military Leaders',
  'Movie Stars (Dead)',
  'Movie Stars (Living)',
  'Movie titles',
  'Movies Shown On TV',
  'Musical groups',
  'Musical instruments',
  'Names used in songs',
  'Nationalities',
  'Newscasters/Journalists',
  'Nicknames',
  'Notorious people',
  'Nouns',
  'Occupations',
  'Ocean things',
  'Offensive words',
  'Olympic events',
  'On The Wine List',
  'Parks',
  'Parts of the body',
  'People Who Go Door To Door',
  'People Who Work Alone',
  'People Who Work At Night',
  'People You Admire',
  'People You Avoid',
  'Personality traits',
  'Pets',
  'Pizza toppings',
  'Places From National Geographic',
  'Places in Europe',
  'Places In North America',
  'Places In Your Town',
  'Places Not On Earth',
  'Places to hangout',
  'Places With A High Altitude',
  'Places You Wouldn’t Want To Live',
  'Political Figures',
  'Produce',
  'Provinces or States',
  'Reasons To Be Absent',
  'Reasons to call 911',
  'Reasons To Go To The Principal’s Office',
  'Reasons to make a phone call',
  'Reasons to quit your job',
  'Reasons to take out a loan',
  'Reptiles/Amphibians',
  'Restaurants',
  'Sandwiches',
  'School subjects',
  'School supplies',
  'Science Terms',
  'Seafood',
  'Sex Symbols',
  'Shows You Don’t Like',
  'Singers',
  'Snack Foods',
  'Soft Drinks',
  'Software',
  'Someone From Your Past',
  'Something you keep hidden',
  'Something you’re afraid of',
  'Song titles',
  'Spices/Herbs',
  'Spicy foods',
  'Sporting Events',
  'Sports equipment',
  'Sports Figures',
  'Sports Played Inside',
  'Sports played outdoors',
  'Sports Stars',
  'Sports Terms',
  'Sports',
  'Stars Who Appear In Both TV And Movies',
  'States',
  'Stones/Gems',
  'Store names',
  'Team Names',
  'Television stars',
  'Terms of endearment',
  'Things Animals Eat',
  'Things at a carnival',
  'Things at a circus',
  'Things at a football game',
  'Things found at a bar',
  'Things Found In A Cafeteria',
  'Things found in a desk',
  'Things found in a hospital',
  'Things Found In A Salad Bar',
  'Things Found In Lockers',
  'Things found in New York',
  'Things Found In The Basement',
  'Things Found In The Water',
  'Things From A Stationery Store',
  'Things in A Classroom',
  'Things in a grocery store',
  'Things in a medicine cabinet',
  'Things in a park',
  'Things in the kitchen',
  'Things in the sky',
  'Things Sold On Commercials',
  'Things that are black',
  'Things that are cold',
  'Things that are hot',
  'Things that are Loud',
  'Things that are Red',
  'Things that are round',
  'Things that are square',
  'Things that are sticky',
  'Things that are White',
  'Things that can get you fired',
  'Things that can kill you',
  'Things That Feel Hot',
  'Things That Feel Soft',
  'Things that grow',
  'Things that have buttons',
  'Things that have spots',
  'Things that have stripes',
  'Things that have wheels',
  'Things that jump/bounce',
  'Things that make you smile',
  'Things That Smell Bad',
  'Things That Smell Good',
  'Things That Taste Spicy',
  'Things that use a remote',
  'Things to do at a party',
  'Things to do on a date',
  'Things With Stripes',
  'Things with tails',
  'Things Worn From The Waist Up',
  'Things you buy for kids',
  'Things You Can See',
  'Things You Carry',
  'Things you do at work',
  'Things you do everyday',
  'Things You Do In Study Hall',
  'Things You Do Tn P.E.',
  'Things You Do While Watching TV',
  'Things You Don\'t Want To Hear',
  'Things you get in the mail',
  'Things you get tickets for',
  'Things you make',
  'Things You Need Tickets To See',
  'Things you replace',
  'Things you save up to buy',
  'Things you see at the zoo',
  'Things You See In A City',
  'Things you shouldn’t touch',
  'Things You Shouldn’t Touch',
  'Things You Shout At Officials',
  'Things you shout',
  'Things you sit/on',
  'Things you store items in',
  'Things You Study In Geography',
  'Things You Study In History',
  'Things you throw away',
  'Things you wear',
  'Things you’re allergic to',
  'Things You’ve Never Tasted',
  'Titles people can have',
  'Tools',
  'Tourist attractions',
  'Toys',
  'Trees',
  'TV Character Names',
  'TV Shows',
  'TV Stars',
  'Types of drinks',
  'Types of weather',
  'Vacation spots',
  'Vegetables',
  'Video games',
  'Villains',
  'Warm Climates',
  'Ways to get from here to there',
  'Ways to kill time',
  'Weapons',
  'Websites',
  'Weekend Activities',
  'Wireless things',
  'Words associated with exercise',
  'Words associated with money',
  'Words associated with winter',
  'Words Ending In “-ed”',
  'Words ending in “-n”',
  'Words Ending In “Ly”',
  'Words That End In “-ing”',
  'Words with double letters',
  'Words With Double Letters',
  'World leaders/Politicians',
  'Zoo Animals'
]